[package]
name = "threadpools"
version = "0.1.0"
authors = ["aevans <aevans48@simplrsinsites.com>"]
edition = "2018"

[dependencies]
num_cpus = "0.2"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
bincode = "1.1.3"